---
- name: systemd daemon-reload for tailscale-mgmt
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  listen: tailscaled-mgmt unit changed

- name: restart tailscaled-mgmt
  become: true
  ansible.builtin.systemd:
    name: tailscaled-mgmt.service
    state: restarted
  listen: tailscaled-mgmt unit changed

- name: systemd daemon-reload for tsmgmt-route-pin
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  listen: tsmgmt-route-pin unit changed

- name: restart tsmgmt-route-pin
  become: true
  ansible.builtin.systemd:
    name: tsmgmt-route-pin.service
    state: restarted
  listen: tsmgmt-route-pin unit changed
